Refactor the websocket handling in Nova
novaframework/nova pull request #161
Opened 2021-12-30 12:39 UTC by burbas

I realized that the websocket plugins wouldn't work with the previous implementation so I sat down and rewrote parts of it. I also incorporated the handler-idea into websockets aswell.

2021-12-30 12:49 UTC, Taure commented
It looks ok, but I will test it with my test app and see if websocket works. :)

2021-12-31 10:48 UTC, Taure requested changes
```2021-12-30T14:14:19.692464+01:00 error: crasher: initial call: cowboy_clear:connection_process/4, pid: <0.2416.0>, registered_name: [], error: {function_clause,[{nova_ws_handler,terminate,[{crash,error,function_clause},#{host => <<"localhost">>,method => <<"GET">>,path => <<"/ws/wohoo">>,peer => {{127,0,0,1},58506},port => 8080,qs => <<>>,scheme => <<"http">>,version => 'HTTP/1.1'},{ok,#{controller_data => <<"wohoo">>,mod => nova_request_ws,module => nova_request_ws,plugins => [{pre_request,[{nova_request_plugin,#{decode_json_body => true,parse_qs => true,read_urlencoded_body => true}}]}]}}],[{file,"/home/daniel/project/nova_request_app/_build/default/lib/nova/src/nova_ws_handler.erl"},{line,67}]},{cowboy_websocket,handler_call,6,[{file,"/home/daniel/project/nova_request_app/_build/default/lib/cowboy/src/cowboy_websocket.erl"},{line,564}]},{cowboy_http,loop,1,[{file,"/home/daniel/project/nova_request_app/_build/default/lib/cowboy/src/cowboy_http.erl"},{line,257}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}, ancestors: [<0.2384.0>,<0.2383.0>,ranch_sup,<0.2356.0>], message_queue_len: 0, messages: [], links: [#Port<0.18>,<0.2384.0>], dictionary: [{rand_seed,{#{bits => 58,jump => #Fun<rand.3.92093067>,next => #Fun<rand.0.92093067>,type => exsss,uniform => #Fun<rand.1.92093067>,uniform_n => #Fun<rand.2.92093067>},[189041614911993767|163146785768922443]}}], trap_exit: true, status: running, heap_size: 1598, stack_size: 29, reductions: 11399; neighbours:
> >  2021-12-30T14:14:19.693001+01:00 error: Ranch listener nova_listener had connection process started with cowboy_clear:start_link/4 at <0.2416.0> exit with reason: {function_clause,[{nova_ws_handler,terminate,[{crash,error,function_clause},#{host => <<"localhost">>,method => <<"GET">>,path => <<"/ws/wohoo">>,peer => {{127,0,0,1},58506},port => 8080,qs => <<>>,scheme => <<"http">>,version => 'HTTP/1.1'},{ok,#{controller_data => <<"wohoo">>,mod => nova_request_ws,module => nova_request_ws,plugins => [{pre_request,[{nova_request_plugin,#{decode_json_body => true,parse_qs => true,read_urlencoded_body => true}}]}]}}],[{file,"/home/daniel/project/nova_request_app/_build/default/lib/nova/src/nova_ws_handler.erl"},{line,67}]},{cowboy_websocket,handler_call,6,[{file,"/home/daniel/project/nova_request_app/_build/default/lib/cowboy/src/cowboy_websocket.erl"},{line,564}]},{cowboy_http,loop,1,[{file,"/home/daniel/project/nova_request_app/_build/default/lib/cowboy/src/cowboy_http.erl"},{line,257}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}```

Got a crash

2022-01-15 20:46 UTC, burbas commented
@Taure Made a new commit on this. Updated our flow in how we are handling the result of a websocket-request. According to cowboy 2.7 the proper response is `{commands(), State}` (https://ninenines.eu/docs/en/cowboy/2.9/manual/cowboy_websocket/). So now we can send multiple frames/commands in one request (And plugins can also utilize this).

2022-01-15 20:50 UTC, Taure approved these changes

2022-01-15 20:51 UTC, Taure approved these changes
Fix dialyzer warnings and we can merge this

2022-01-16 21:05 UTC, merged